"""EvaluatorStage — post-commit goal evaluation agent.

Runs as the final stage of the pipeline **only** when the pipeline was
triggered by the goals scheduler.  Reads current repository state (PLAN.md,
DASHBOARD.md, supervisor report, git log), asks the configured agent CLI to
evaluate goal achievement, writes a report to ``.dev/logs/``, and
optionally updates the original goal file so the goals scheduler can schedule
the next iteration.

Next-goal strategies
--------------------
``"none"``    — Write the evaluation report only; do not touch the goal file.
``"suggest"`` — Append the evaluation report + suggestions to the goal file
                for human review.  The goals scheduler will re-schedule this
                goal on the next interval so a human can decide what to do.
``"auto"``    — Overwrite the goal file with the next goal generated by the
                evaluator agent.  The goals scheduler then picks it up
                automatically.

Thread safety
-------------
All filesystem writes happen on the pipeline thread; no shared mutable state.
"""
from __future__ import annotations

import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, TextIO

from dormammu.agent.prompt_identity import prepend_cli_identity
from dormammu.daemon.cli_output import select_agent_output
from dormammu.daemon.rules import build_rule_prompt, load_rule_text
from dormammu.results import ResultStatus, ResultVerdict, StageResult, parse_final_evaluator_verdict
from dormammu.workspace import create_temp_text_file, remove_temp_path

if TYPE_CHECKING:
    from dormammu.daemon.goals_config import EvaluatorConfig

# Regex to extract the next-goal block when strategy is "auto".
# The evaluator is instructed to wrap the next goal in these delimiters.
_NEXT_GOAL_RE = re.compile(
    r"<!-- next_goal_start -->(.*?)<!-- next_goal_end -->",
    re.DOTALL,
)

_MODEL_FLAGS: dict[str, str] = {
    "claude": "--model",
    "claude-code": "--model",
    "gemini": "--model",
    "codex": "-m",
    "aider": "--model",
}


@dataclass
class EvaluatorRequest:
    """Input parameters for a single evaluator run."""

    cli: Path
    model: str | None
    goal_file_path: Path        # original goal .md file (may be rewritten)
    goal_text: str              # content of the original goal file
    repo_root: Path
    dev_dir: Path               # scoped session .dev/ directory
    tmp_dir: Path
    agents_dir: Path
    runtime_paths_text: str
    next_goal_strategy: str     # none | suggest | auto
    stem: str                   # prompt stem (used for output doc naming)
    date_str: str


class EvaluatorStage:
    """Runs the post-commit evaluation step for a single pipeline execution."""

    def __init__(
        self,
        *,
        progress_stream: TextIO | None = None,
    ) -> None:
        self._progress_stream = progress_stream or sys.stderr

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self, request: EvaluatorRequest) -> StageResult:
        """Execute the evaluator and return a canonical stage result."""
        self._log("evaluator: stage starting")

        prompt = self._build_prompt(request)
        output = self._call_once(request, prompt)

        if output is None:
            self._log("evaluator: agent call failed — skipping goal file update")
            return StageResult(
                role="evaluator",
                stage_name="final_evaluator",
                status=ResultStatus.FAILED,
                verdict=ResultVerdict.UNKNOWN,
                summary="Evaluator agent execution failed before a verdict was produced.",
                metadata={"goal_file_updated": False},
            )

        verdict = self._parse_verdict(output)
        self._log(f"evaluator: verdict = {verdict}")

        report_path = self._write_report(request, output)

        has_valid_verdict = verdict != ResultVerdict.UNKNOWN
        goal_file_updated = (
            self._update_goal_file(request, output, verdict)
            if has_valid_verdict
            else False
        )

        self._log(
            f"evaluator: stage completed "
            f"(verdict={verdict}, goal_file_updated={goal_file_updated})"
        )
        return StageResult(
            role="evaluator",
            stage_name="final_evaluator",
            status=ResultStatus.COMPLETED if has_valid_verdict else ResultStatus.FAILED,
            verdict=verdict,
            output=output,
            report_path=report_path,
            summary=(
                "Post-commit goal evaluation completed."
                if has_valid_verdict
                else "Evaluator output did not include a valid 'VERDICT:' line."
            ),
            metadata={"goal_file_updated": goal_file_updated},
        )

    # ------------------------------------------------------------------
    # Prompt construction
    # ------------------------------------------------------------------

    def _build_prompt(self, req: EvaluatorRequest) -> str:
        rule_text = load_rule_text(req.agents_dir, "evaluator-final.md")
        plan_text = self._read_file(req.dev_dir / "PLAN.md")
        dashboard_text = self._read_file(req.dev_dir / "DASHBOARD.md")
        workflows_text = self._read_file(req.dev_dir / "WORKFLOWS.md")
        supervisor_report = self._read_file(req.dev_dir / "supervisor_report.md")
        git_summary = self._read_git_summary(req.repo_root)
        output_path = req.dev_dir / "logs" / f"{req.date_str}_evaluator_{req.stem}.md"
        return build_rule_prompt(
            rule_text,
            runtime_paths_text=req.runtime_paths_text,
            sections=(
                ("Original Goal", req.goal_text),
                ("Completed Plan", plan_text),
                ("Dashboard", dashboard_text),
                ("Workflows", workflows_text),
                ("Supervisor Report", supervisor_report),
                ("Recent Git Activity", git_summary),
                ("Next Goal Strategy", self._next_goal_strategy_instructions(req.next_goal_strategy)),
                ("Expected Output Path", str(output_path)),
            ),
        )

    # ------------------------------------------------------------------
    # Agent invocation
    # ------------------------------------------------------------------

    def _call_once(self, req: EvaluatorRequest, prompt: str) -> str | None:
        """Run the evaluator CLI once and return stdout, or None on failure."""
        from dormammu.agent.presets import preset_for_executable_name  # noqa: PLC0415

        executable_name = req.cli.name
        preset = preset_for_executable_name(executable_name)
        prompt = prepend_cli_identity(prompt, req.cli)

        args: list[str] = [str(req.cli)]
        stdin_input: str | None = None
        tmp_path: Path | None = None

        if preset is not None:
            args.extend(preset.command_prefix)
            args.extend(preset.default_extra_args)

        if req.model is not None:
            flag = _MODEL_FLAGS.get(executable_name.lower())
            if flag:
                args.extend([flag, req.model])

        if preset is not None and preset.prompt_positional:
            args.append(prompt)
        elif preset is not None and preset.prompt_file_flag:
            tmp_path = create_temp_text_file(
                req.tmp_dir,
                prefix="evaluator-",
                suffix=".md",
                content=prompt,
            )
            args.extend([preset.prompt_file_flag, str(tmp_path)])
        elif preset is not None and preset.prompt_arg_flag:
            args.extend([preset.prompt_arg_flag, prompt])
        else:
            stdin_input = prompt

        try:
            result = subprocess.run(
                args,
                input=stdin_input,
                capture_output=True,
                text=True,
                cwd=str(req.repo_root),
            )
            self._log(f"evaluator: agent exit code: {result.returncode}")
            return select_agent_output(result.stdout, result.stderr)
        except Exception as exc:
            self._log(f"evaluator: agent call failed: {exc}")
            return None
        finally:
            remove_temp_path(tmp_path)

    # ------------------------------------------------------------------
    # Output handling
    # ------------------------------------------------------------------

    def _parse_verdict(self, output: str) -> str:
        return parse_final_evaluator_verdict(output).value

    def _write_report(self, req: EvaluatorRequest, output: str) -> Path | None:
        try:
            doc_dir = req.dev_dir / "logs"
            doc_dir.mkdir(parents=True, exist_ok=True)
            doc_path = doc_dir / f"{req.date_str}_evaluator_{req.stem}.md"
            doc_path.write_text(
                f"# Evaluator — {req.stem}\n\n{output}",
                encoding="utf-8",
            )
            self._log(f"evaluator: report written to {doc_path}")
            return doc_path
        except Exception as exc:
            self._log(f"evaluator: failed to write report: {exc}")
            return None

    def _update_goal_file(
        self, req: EvaluatorRequest, output: str, verdict: str
    ) -> bool:
        """Update the original goal file according to next_goal_strategy.

        Returns True when the goal file was written.
        """
        strategy = req.next_goal_strategy

        if strategy == "none":
            return False

        if strategy == "suggest":
            return self._append_suggestions_to_goal(req, output, verdict)

        if strategy == "auto":
            return self._overwrite_goal_with_next(req, output, verdict)

        return False

    def _append_suggestions_to_goal(
        self, req: EvaluatorRequest, output: str, verdict: str
    ) -> bool:
        """Append evaluation summary to the goal file for human review."""
        try:
            timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            separator = (
                f"\n\n---\n\n"
                f"<!-- evaluation: {timestamp} | verdict: {verdict} -->\n\n"
                f"## Evaluation ({timestamp})\n\n"
                f"**Verdict**: {verdict}\n\n"
                + self._extract_evaluation_body(output)
            )
            existing = req.goal_file_path.read_text(encoding="utf-8")
            req.goal_file_path.write_text(existing + separator, encoding="utf-8")
            self._log(
                f"evaluator: appended evaluation to goal file "
                f"{req.goal_file_path.name}"
            )
            return True
        except Exception as exc:
            self._log(f"evaluator: failed to update goal file: {exc}")
            return False

    def _overwrite_goal_with_next(
        self, req: EvaluatorRequest, output: str, verdict: str
    ) -> bool:
        """Overwrite the goal file with the next goal extracted from agent output."""
        match = _NEXT_GOAL_RE.search(output)
        if not match:
            self._log(
                "evaluator: next_goal_strategy=auto but no "
                "<!-- next_goal_start --> ... <!-- next_goal_end --> block found "
                "in agent output — goal file not updated"
            )
            return False

        next_goal = match.group(1).strip()
        if not next_goal:
            self._log(
                "evaluator: next goal block is empty — goal file not updated"
            )
            return False

        try:
            req.goal_file_path.write_text(next_goal + "\n", encoding="utf-8")
            self._log(
                f"evaluator: goal file overwritten with next goal "
                f"({req.goal_file_path.name})"
            )
            return True
        except Exception as exc:
            self._log(f"evaluator: failed to overwrite goal file: {exc}")
            return False

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _read_file(path: Path) -> str | None:
        try:
            return path.read_text(encoding="utf-8")
        except OSError:
            return None

    @staticmethod
    def _read_git_summary(repo_root: Path) -> str | None:
        try:
            result = subprocess.run(
                ["git", "log", "-3", "--oneline", "--stat"],
                capture_output=True,
                text=True,
                cwd=str(repo_root),
                timeout=15,
            )
            return result.stdout.strip() or None
        except Exception:
            return None

    @staticmethod
    def _extract_evaluation_body(output: str) -> str:
        """Return the agent output with the next-goal block removed."""
        return _NEXT_GOAL_RE.sub("", output).strip()

    @staticmethod
    def _next_goal_strategy_instructions(strategy: str) -> str:
        if strategy == "auto":
            return (
                "After the verdict line, generate the next goal inside these exact delimiters:\n"
                "<!-- next_goal_start -->\n"
                "<next goal content in Markdown>\n"
                "<!-- next_goal_end -->"
            )
        if strategy == "suggest":
            return (
                "After the verdict line, add a `## Suggestions for Next Cycle` "
                "section for human review. Do not output a next-goal block."
            )
        return "Do not output a next-goal block after the verdict line."

    def _log(self, message: str) -> None:
        print(message, file=self._progress_stream)
        self._progress_stream.flush()


def resolve_evaluator_cli(
    evaluator_config: "EvaluatorConfig",
    agents_evaluator_cli: Path | None,
    active_agent_cli: Path | None,
) -> Path | None:
    """Resolve the effective CLI for the evaluator stage.

    Priority:
    1. ``evaluator_config.cli`` — explicit setting in goals.evaluator
    2. ``agents_evaluator_cli`` — dormammu.json agents.evaluator.cli
    3. ``active_agent_cli`` — global fallback
    """
    return (
        evaluator_config.cli
        or agents_evaluator_cli
        or active_agent_cli
    )


def resolve_evaluator_model(
    evaluator_config: "EvaluatorConfig",
    agents_evaluator_model: str | None,
) -> str | None:
    """Resolve the effective model for the evaluator stage.

    Priority:
    1. ``evaluator_config.model`` — explicit setting in goals.evaluator
    2. ``agents_evaluator_model`` — dormammu.json agents.evaluator.model
    """
    return evaluator_config.model or agents_evaluator_model
