from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

_MIN_INTERVAL_MINUTES = 1
DEFAULT_AGENT_TIMEOUT_SECONDS = 600  # 10 minutes

VALID_NEXT_GOAL_STRATEGIES = ("none", "suggest", "auto")


@dataclass(frozen=True, slots=True)
class EvaluatorConfig:
    """Configuration for the post-commit evaluator stage.

    ``enabled`` — whether to run the evaluator after each committer stage.
    ``cli`` — agent CLI path override (falls back to agents.evaluator or
    active_agent_cli when None).
    ``model`` — model override (no ``--model`` flag when None).
    ``next_goal_strategy`` — what to do with the original goal file:
      ``"none"``    — do not touch the goal file (evaluation report only).
      ``"suggest"`` — append evaluation + suggestions to the goal file for
                      human review; does not trigger automatic re-scheduling.
      ``"auto"``    — overwrite the goal file with the next goal generated by
                      the evaluator so the goals scheduler picks it up on the
                      next interval.
    """

    enabled: bool = False
    cli: Path | None = None
    model: str | None = None
    next_goal_strategy: str = "none"

    def to_dict(self) -> dict[str, object]:
        return {
            "enabled": self.enabled,
            "cli": str(self.cli) if self.cli is not None else None,
            "model": self.model,
            "next_goal_strategy": self.next_goal_strategy,
        }


def parse_evaluator_config(
    value: Any,
    *,
    config_path: Path,
) -> EvaluatorConfig | None:
    """Parse the ``goals.evaluator`` section of a daemonize config file.

    Returns ``None`` when the section is absent (evaluator disabled).
    """
    if value is None:
        return None

    source = str(config_path)
    if not isinstance(value, Mapping):
        raise RuntimeError(
            f"goals.evaluator must be a JSON object in {source}"
        )

    enabled_raw = value.get("enabled", False)
    enabled = bool(enabled_raw)

    cli_raw = value.get("cli")
    cli: Path | None = None
    if cli_raw is not None:
        if not isinstance(cli_raw, str) or not cli_raw.strip():
            raise RuntimeError(
                f"goals.evaluator.cli must be a non-empty string in {source}"
            )
        candidate = Path(cli_raw.strip()).expanduser()
        cli = (
            candidate
            if candidate.is_absolute()
            else (config_path.parent / candidate).resolve()
            if ("/" in cli_raw or cli_raw.startswith("."))
            else candidate
        )

    model_raw = value.get("model")
    model: str | None = None
    if model_raw is not None:
        if not isinstance(model_raw, str) or not model_raw.strip():
            raise RuntimeError(
                f"goals.evaluator.model must be a non-empty string in {source}"
            )
        model = model_raw.strip()

    strategy_raw = value.get("next_goal_strategy", "none")
    if strategy_raw not in VALID_NEXT_GOAL_STRATEGIES:
        raise RuntimeError(
            f"goals.evaluator.next_goal_strategy must be one of "
            f"{VALID_NEXT_GOAL_STRATEGIES} in {source}"
        )

    return EvaluatorConfig(
        enabled=enabled,
        cli=cli,
        model=model,
        next_goal_strategy=str(strategy_raw),
    )


@dataclass(frozen=True, slots=True)
class GoalsConfig:
    """Configuration for the goals-based prompt auto-generation feature.

    ``path`` — directory that contains goal ``.md`` files.
    ``interval_minutes`` — how often (in minutes) to process all goal files
    and emit new prompts.  Minimum 1.
    ``agent_timeout_seconds`` — per-role-agent subprocess timeout in seconds.
    Defaults to 600 (10 minutes).
    ``evaluator`` — optional evaluator configuration.  When set and
    ``evaluator.enabled`` is true the evaluator stage runs after each
    committer stage that was triggered by the goals scheduler.
    """

    path: Path
    interval_minutes: int
    agent_timeout_seconds: int = DEFAULT_AGENT_TIMEOUT_SECONDS
    evaluator: EvaluatorConfig | None = None

    def to_dict(self) -> dict[str, object]:
        return {
            "path": str(self.path),
            "interval_minutes": self.interval_minutes,
            "agent_timeout_seconds": self.agent_timeout_seconds,
            "evaluator": self.evaluator.to_dict() if self.evaluator is not None else None,
        }


def parse_goals_config(
    value: Any,
    *,
    config_path: Path,
) -> GoalsConfig | None:
    """Parse the ``goals`` section of a daemonize config file.

    Returns ``None`` when the section is absent (goals feature disabled).
    ``config_path`` is used both for error messages and for resolving
    relative paths.
    """
    if value is None:
        return None

    source = str(config_path)
    if not isinstance(value, Mapping):
        raise RuntimeError(f"goals must be a JSON object in {source}")

    path_raw = value.get("path")
    if not isinstance(path_raw, str) or not path_raw.strip():
        raise RuntimeError(
            f"goals.path must be a non-empty string in {source}"
        )
    candidate = Path(path_raw.strip()).expanduser()
    goals_path = (
        candidate
        if candidate.is_absolute()
        else (config_path.parent / candidate).resolve()
    )

    interval_raw = value.get("interval_minutes", 60)
    try:
        interval_minutes = int(interval_raw)
    except (TypeError, ValueError) as exc:
        raise RuntimeError(
            f"goals.interval_minutes must be an integer in {source}"
        ) from exc
    if interval_minutes < _MIN_INTERVAL_MINUTES:
        raise RuntimeError(
            f"goals.interval_minutes must be >= {_MIN_INTERVAL_MINUTES} in {source}"
        )

    timeout_raw = value.get("agent_timeout_seconds", DEFAULT_AGENT_TIMEOUT_SECONDS)
    try:
        agent_timeout_seconds = int(timeout_raw)
    except (TypeError, ValueError) as exc:
        raise RuntimeError(
            f"goals.agent_timeout_seconds must be an integer in {source}"
        ) from exc
    if agent_timeout_seconds < 1:
        raise RuntimeError(
            f"goals.agent_timeout_seconds must be >= 1 in {source}"
        )

    evaluator = parse_evaluator_config(
        value.get("evaluator"),
        config_path=config_path,
    )

    return GoalsConfig(
        path=goals_path,
        interval_minutes=interval_minutes,
        agent_timeout_seconds=agent_timeout_seconds,
        evaluator=evaluator,
    )
